#
# Makefile for MMC/SD host controller drivers
#

obj-$(CONFIG_MSC0_JZ4750)	+= msc/ dma/ gpio/ jz_mmc_controller.o
obj-$(CONFIG_MSC1_JZ4750)	+= msc/ dma/ gpio/ jz_mmc_controller.o
obj-$(CONFIG_MSC0_JZ4760)	+= msc/ dma/ gpio/ jz_mmc_controller.o
obj-$(CONFIG_MSC1_JZ4760)	+= msc/ dma/ gpio/ jz_mmc_controller.o
obj-$(CONFIG_MSC0_JZ4770)	+= msc/ dma/ gpio/ charsd/ jz_mmc_controller.o
obj-$(CONFIG_MSC1_JZ4770)	+= msc/ dma/ gpio/ charsd/ jz_mmc_controller.o
obj-$(CONFIG_MSC2_JZ4770)	+= msc/ dma/ gpio/  charsd/ jz_mmc_controller.o
