
obj-$(CONFIG_ISP)		+= camera_source/isp/
obj-$(CONFIG_OV2640)		+= camera_source/ov2640/
obj-$(CONFIG_OV9650)		+= camera_source/ov9650/

obj-$(CONFIG_JZ_CIM)		+= jz_cim_core.o jz_sensor.o 


obj-$(CONFIG_OV7690)		+= camera_source/ov7690/
obj-$(CONFIG_OV3640)		+= camera_source/ov3640/
obj-$(CONFIG_OV2655)		+= camera_source/ov2655/
obj-$(CONFIG_CM3511)		+= camera_source/cm3511/
obj-$(CONFIG_HI253)			+= camera_source/hi253/
obj-$(CONFIG_BF3703)		+= camera_source/bf3703/
obj-$(CONFIG_JZ_FAKE_SENSOR)	+= camera_source/fake/

obj-$(CONFIG_GC0307)	+= camera_source/gc0307/
obj-$(CONFIG_GC0308)	+= camera_source/gc0308/
obj-$(CONFIG_GC0309)		+= camera_source/gc0309/
obj-$(CONFIG_GC2015)	+= camera_source/gc2015/
obj-$(CONFIG_HI704)		+= camera_source/hi704/
obj-$(CONFIG_OV2655_Z800)	+= camera_source/ov2655_z800/
obj-$(CONFIG_OV7675)            += camera_source/ov7675/
obj-$(CONFIG_CM3511_Z800)	+= camera_source/cm3511_z800/
obj-$(CONFIG_F2655)		+= camera_source/f2655/
obj-$(CONFIG_SIV120B)		+= camera_source/siv120b/
obj-$(CONFIG_GT2005)		+= camera_source/gt2005/
