#
# Makefile for MMC/SD host controller drivers
#

obj-$(CONFIG_MSC0_JZ4750)	+= jz_mmc_gpio.o
obj-$(CONFIG_MSC1_JZ4750)	+= jz_mmc_gpio.o
obj-$(CONFIG_MSC0_JZ4760)	+= jz_mmc_gpio.o
obj-$(CONFIG_MSC1_JZ4760)	+= jz_mmc_gpio.o
obj-$(CONFIG_MSC0_JZ4770)	+= jz_mmc_gpio.o
obj-$(CONFIG_MSC1_JZ4770)	+= jz_mmc_gpio.o
obj-$(CONFIG_MSC2_JZ4770)	+= jz_mmc_gpio.o
