#
# Makefile for MMC/SD host controller drivers
#

obj-$(CONFIG_MSC0_JZ4750)	+= controller/ jz_mmc_main.o
obj-$(CONFIG_MSC1_JZ4750)	+= controller/ jz_mmc_main.o
obj-$(CONFIG_MSC0_JZ4760)	+= controller/ jz_mmc_main.o
obj-$(CONFIG_MSC1_JZ4760)	+= controller/ jz_mmc_main.o
obj-$(CONFIG_MSC0_JZ4770)	+= controller/ jz_mmc_main.o
obj-$(CONFIG_MSC1_JZ4770)	+= controller/ jz_mmc_main.o
obj-$(CONFIG_MSC2_JZ4770)	+= controller/ jz_mmc_main.o