obj-$(CONFIG_ANDROID_LCD_AT070TN93)		+= linden-lcd.o
obj-$(CONFIG_ANDROID_LCD_KD080D3_40NB_A3)	+= linden-lcd.o
obj-$(CONFIG_ANDROID_LCD_HB080D_24E)		+= linden-lcd.o
obj-$(CONFIG_ANDROID_LCD_BYD_BM1024600)		+= linden-lcd-byd-1024600.o
obj-y						+= linden-misc.o
obj-$(CONFIG_I2S_DLV_4770)			+= linden-audio.o
obj-y						+= linden-pm.o
