obj-$(CONFIG_JZ4770_NPM701)		+= npm701/
obj-$(CONFIG_JZ4770_NPM702)		+= npm702/
obj-$(CONFIG_JZ4770_NPM703)		+= npm703/
obj-$(CONFIG_JZ4770_AURORA)		+= aurora/
obj-$(CONFIG_JZ4770_O1)			+= o1/
obj-$(CONFIG_JZ4770_LINDEN)		+= linden/
obj-$(CONFIG_JZ4770_PS47)		+= ps47/
obj-$(CONFIG_JZ4770_PI3800)		+= pi3800/
