obj-$(CONFIG_ANDROID_LCD_AT070TN93)		+= pi3800-lcd.o
obj-$(CONFIG_ANDROID_LCD_KD080D3_40NB_A3)	+= pi3800-lcd.o
obj-$(CONFIG_ANDROID_LCD_HB080D_24E)		+= pi3800-lcd.o
obj-$(CONFIG_ANDROID_LCD_BYD_BM1024600)		+= pi3800-lcd-byd-1024600.o
obj-$(CONFIG_ANDROID_LCD_AT070TNA2)		+= pi3800-lcd.o
obj-y						+= pi3800-misc.o
obj-$(CONFIG_I2S_DLV_4770)			+= pi3800-audio.o
obj-y						+= pi3800-pm.o
