/* header file for JZ CODEC */

#if defined(CONFIG_SOC_JZ4760) || defined(CONFIG_SOC_JZ4760B)
#include "./xb4760/jz4760_dlv.h"
#include "./xb4760/jz4760_route_conf.h"
#elif defined(CONFIG_SOC_JZ4770)
#include "./xb4770/jz4770_dlv.h"
#include "./xb4770/jz4770_route_conf.h"
#endif

#ifndef _JZ_CODEC_H_
#define _JZ_CODEC_H_

enum codec_ioctl_cmd_t {
	CODEC_INIT,
	CODEC_TURN_OFF,
	CODEC_SHUTDOWN,
	CODEC_RESET,
	CODEC_SUSPEND,
	CODEC_RESUME,
	CODEC_ANTI_POP,
	CODEC_SET_ROUTE,
	CODEC_SET_DEVICE,
	CODEC_SET_STANDBY,
	CODEC_SET_RECORD_RATE,
	CODEC_SET_RECORD_DATA_WIDTH,
	CODEC_SET_MIC_VOLUME,
	CODEC_SET_RECORD_CHANNEL,
	CODEC_SET_REPLAY_RATE,
	CODEC_SET_REPLAY_DATA_WIDTH,
	CODEC_SET_REPLAY_VOLUME,
	CODEC_SET_REPLAY_CHANNEL,
	CODEC_SET_ADC_LRSWAP,
	CODEC_CLEAR_ADC_LRSWAP,
	CODEC_SET_DAC_LRSWAP,
	CODEC_CLEAR_DAC_LRSWAP,
	CODEC_DAC_MUTE,
	CODEC_DEBUG_ROUTINE
};

enum device_t {
	SND_DEVICE_DEFAULT = 0,
	SND_DEVICE_CURRENT,
	SND_DEVICE_HANDSET,
	SND_DEVICE_HEADSET,
	SND_DEVICE_SPEAKER,
	SND_DEVICE_BT,
	SND_DEVICE_BT_EC_OFF,
	SND_DEVICE_HEADSET_AND_SPEAKER,
	SND_DEVICE_TTY_FULL,
	SND_DEVICE_CARKIT,
	SND_DEVICE_FM_SPEAKER,
	SND_DEVICE_FM_HEADSET,
	SND_DEVICE_NO_MIC_HEADSET,
	SND_DEVICE_HDMI,
	SND_DEVICE_COUNT
};

void register_jz_codecs(void *func);
void dump_dlv_regs(void);

#define SND_SET_STANDBY _IOW(SND_IOCTL_MAGIC, 4, unsigned int *)

// Deprecate !!!
#define USE_NONE		1
#define USE_MIC			2
#define USE_LINEIN		3

// For file ops
#define CODEC_WMODE		(1 << 0)
#define CODEC_RMODE		(1 << 1)
#define CODEC_WRMODE		(CODEC_WMODE | CODEC_RMODE)

#endif /* _JZ_CODEC_H_ */
